/* ------------------ */
/* --- SENSOR ADC --- */
/* ------------------ */
#define ASC_SENSORADC_SEL_RESET 		242
#define ASC_SENSORADC_SEL_CONVERT 		243
#define ASC_SENSORADC_SEL_PGA_AMPLIFY 	244

#define ASC_SENSORADC_PGA_GAIN_7  		773
#define ASC_SENSORADC_PGA_GAIN_6		800
#define ASC_SENSORADC_PGA_GAIN_5 		771
#define ASC_SENSORADC_PGA_GAIN_4 		770
#define ASC_SENSORADC_PGA_GAIN_3		769
#define ASC_SENSORADC_PGA_GAIN_2		768
#define ASC_SENSORADC_PGA_GAIN_1 		767
#define ASC_SENSORADC_PGA_GAIN_0 		766

#define ASC_SENSORADC_ADC_SETTLE_7		823
#define ASC_SENSORADC_ADC_SETTLE_6		822
#define ASC_SENSORADC_ADC_SETTLE_5		821
#define ASC_SENSORADC_ADC_SETTLE_4		820
#define ASC_SENSORADC_ADC_SETTLE_3		819
#define ASC_SENSORADC_ADC_SETTLE_2		818
#define ASC_SENSORADC_ADC_SETTLE_1		817
#define ASC_SENSORADC_ADC_SETTLE_0		816

#define ASC_SENSORADC_BGR_TUNE_6		779
#define ASC_SENSORADC_BGR_TUNE_5		780
#define ASC_SENSORADC_BGR_TUNE_4		781
#define ASC_SENSORADC_BGR_TUNE_3		782
#define ASC_SENSORADC_BGR_TUNE_2		783
#define ASC_SENSORADC_BGR_TUNE_1		784
#define ASC_SENSORADC_BGR_TUNE_0		778

#define ASC_SENSORADC_CONSTGM_TUNE_7	758
#define ASC_SENSORADC_CONSTGM_TUNE_6	759
#define ASC_SENSORADC_CONSTGM_TUNE_5	760
#define ASC_SENSORADC_CONSTGM_TUNE_4	761
#define ASC_SENSORADC_CONSTGM_TUNE_3	762
#define ASC_SENSORADC_CONSTGM_TUNE_2	763
#define ASC_SENSORADC_CONSTGM_TUNE_1	764
#define ASC_SENSORADC_CONSTGM_TUNE_0	765

#define ASC_SENSORADC_EN_VBATDIV		798
#define ASC_SENSORADC_EN_LDO			801

#define ASC_SENSORADC_SEL_INPUT_MUX_1	1087
#define ASC_SENSORADC_SEL_INPUT_MUX_0	915

#define ASC_SENSORADC_PGA_BYPASS 		1088